#!/usr/bin/env python3
"""
Convert any audio file (mp3, wav, m4a, ...) into audio_data.h + water_raw.bin
for the ESP8266 water-conservation-alert firmware.

Usage:
    python convert_audio.py my_message.mp3
    python convert_audio.py my_message.wav --drive 3.0 --peak 0.95

Requirements:
    pip install av numpy scipy

What it does (matches the pipeline used to build the audio shipped in this
repo, tuned by ear against this project's hardware - PAM8403/class-D amp +
4-8 ohm speaker via the ESP8266 hardware sigma-delta output on GPIO5):
  1. Decode and resample to 16 kHz mono.
  2. DC-block with an 80 Hz high-pass filter.
  3. Band-limit with a 7 kHz low-pass filter (removes ultrasonic-adjacent
     content and anti-aliases before the final resample).
  4. Normalize, then apply tanh soft-limiting ("drive") for extra loudness
     without hard-clipping.
  5. Scale to a target peak (default 0.95 of full scale) with headroom -
     never touches 100%, so the sigma-delta output never sits at its
     least-linear extremes (0 or 255 duty).
  6. Apply a 5 ms raised-cosine fade in/out so playback starts and ends
     at exact zero (no clicks/pops).
  7. Write water_raw.bin (raw int16 PCM) and audio_data.h (PROGMEM array
     the .ino #includes directly).

Tuning notes:
  --drive controls how much the tanh curve compresses peaks toward the
  target peak level, which raises average loudness (RMS) at the cost of
  some waveform distortion once it saturates. 1.8 is conservative/clean;
  3.0 is noticeably louder; above ~4 speech starts to sound compressed/
  distorted. If your source recording already has strong, consistent
  levels, a lower drive (1.8-2.5) usually sounds cleaner.
"""

import argparse
import math
import sys

import av
import numpy as np
from scipy import signal

SAMPLE_RATE = 16000


def load_and_resample(path, target_rate):
    container = av.open(path)
    stream = container.streams.audio[0]
    resampler = av.AudioResampler(format="s16", layout="mono", rate=target_rate)
    pcm = bytearray()
    for frame in container.decode(stream):
        frame.pts = None
        for resampled in resampler.resample(frame):
            pcm += bytes(resampled.planes[0])
    return np.frombuffer(bytes(pcm), dtype=np.int16).astype(np.float64) / 32768.0


def process(x, drive, peak):
    # DC block
    b, a = signal.butter(2, 80 / (SAMPLE_RATE / 2), "highpass")
    x = signal.filtfilt(b, a, x)

    # Band-limit for speech intelligibility + anti-alias
    b, a = signal.butter(6, 7000 / (SAMPLE_RATE / 2), "lowpass")
    x = signal.filtfilt(b, a, x)

    x = x - np.mean(x)
    peak_now = np.max(np.abs(x))
    if peak_now < 1e-9:
        raise ValueError("Decoded audio is silent - check the input file.")
    x = x / peak_now

    # tanh soft-limit for loudness without hard clipping
    x = np.tanh(drive * x) / np.tanh(drive)
    x = peak * x / np.max(np.abs(x))

    # 5 ms raised-cosine fade in/out
    fade_len = int(0.005 * SAMPLE_RATE)
    window = 0.5 * (1 - np.cos(np.pi * np.arange(fade_len) / fade_len))
    x[:fade_len] *= window
    x[-fade_len:] *= window[::-1]
    x[0] = 0.0
    x[-1] = 0.0

    return x


def write_outputs(x, bin_path, header_path, drive, peak):
    q = np.round(x * 32767).astype(np.int16)
    q.tofile(bin_path)

    duty = (q >> 8) + 128
    rms = float(np.sqrt(np.mean(q.astype(np.float64) ** 2)))
    clipped = int(np.sum(np.abs(q) >= 32767))

    with open(header_path, "w") as f:
        f.write("#pragma once\n#include <Arduino.h>\n\n")
        f.write(f"// 16-bit signed mono PCM @ {SAMPLE_RATE} Hz\n")
        f.write(f"// Generated by convert_audio.py - drive={drive}, peak={peak}\n")
        f.write("// DC-blocked (80Hz HPF), band-limited (7kHz LPF), tanh soft-limited,\n")
        f.write("// 5ms raised-cosine fades, first/last sample == 0.\n")
        f.write(f"#define AUDIO_SAMPLE_RATE {SAMPLE_RATE}\n")
        f.write(f"const uint32_t audioLen = {q.size};\n")
        f.write("const int16_t audioData[] PROGMEM = {\n")
        for i in range(0, q.size, 16):
            f.write(",".join(str(int(v)) for v in q[i:i + 16]) + ",\n")
        f.write("};\n")

    print(f"samples     : {q.size}  ({q.size / SAMPLE_RATE:.2f} s)")
    print(f"peak        : {int(np.max(np.abs(q)))} / 32767")
    print(f"rms         : {int(rms)}")
    print(f"duty range  : {int(duty.min())} .. {int(duty.max())}  (keep this away from 0/255)")
    print(f"hard-clipped: {clipped} samples")
    print(f"wrote {bin_path} and {header_path}")


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("input", help="Source audio file (mp3, wav, m4a, ...)")
    ap.add_argument("--drive", type=float, default=1.8, help="tanh compression drive (default 1.8, try up to ~3.0-3.5 for more loudness)")
    ap.add_argument("--peak", type=float, default=0.95, help="target peak as a fraction of full scale (default 0.95)")
    ap.add_argument("--out-bin", default="water_raw.bin")
    ap.add_argument("--out-header", default="audio_data.h")
    args = ap.parse_args()

    if not (0 < args.peak <= 1.0):
        sys.exit("--peak must be between 0 and 1")

    x = load_and_resample(args.input, SAMPLE_RATE)
    x = process(x, args.drive, args.peak)
    write_outputs(x, args.out_bin, args.out_header, args.drive, args.peak)


if __name__ == "__main__":
    main()
